name: Raz Carcoana
favicon: null
layout_spectrum: 0.04386134003289044
typography_spectrum: 0.4260059737134725
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.21655242191627622
  lightness: 0.9080716744065285
  saturation: 0.14665228594094515
  rhythmicContrast: 0.029249718179926276
purpose: []
